manifest = "f95b34d966ceca5e995434ea4e6e5d15cf947c8f078dfae43357e1bcefb6a9f3"

[[dependency]]
package = "github.com/buckaroo-pm/protobuf"
target = "//:protobuf"

[lock."github.com/buckaroo-pm/protobuf"]
versions = [ "branch=master" ]
revision = "0619332da521aecf8c8d3d8275665ccabf0209ee"
